// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Peredent.Api.Data;

#nullable disable

namespace Peredent.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260926232455_SincronizarSnapshotConScriptsSprint2a4")]
    partial class SincronizarSnapshotConScriptsSprint2a4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Peredent.Api.Models.BloqueoAgenda", b =>
                {
                    b.Property<int>("IdBloqueoAgenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_BloqueoAgenda");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBloqueoAgenda"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreadoEn");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("Fecha");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Motivo");

                    b.HasKey("IdBloqueoAgenda");

                    b.HasIndex("IdUsuario", "Fecha")
                        .IsUnique();

                    b.ToTable("BloqueoAgenda", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Cita");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Inicio");

                    b.Property<int>("IdEstadoCita")
                        .HasColumnType("int")
                        .HasColumnName("ID_EstadoCita");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int")
                        .HasColumnName("ID_Paciente");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    b.Property<string>("NotasAdicionales")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NotasAdicionales");

                    b.HasKey("IdCita");

                    b.HasIndex("IdEstadoCita");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Citas", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.Condicion", b =>
                {
                    b.Property<int>("IdCondicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Condicion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCondicion"));

                    b.Property<string>("NombreCondicion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre_Condicion");

                    b.HasKey("IdCondicion");

                    b.ToTable("Condicion", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.DatosRecetario", b =>
                {
                    b.Property<int>("IdDatosRecetario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DatosRecetario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDatosRecetario"));

                    b.Property<string>("ApellidosOdontologo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ApellidosOdontologo");

                    b.Property<string>("ColegiadoOdontologo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ColegiadoOdontologo");

                    b.Property<string>("CorreoOdontologo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("CorreoOdontologo");

                    b.Property<string>("DireccionOdontologo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DireccionOdontologo");

                    b.Property<string>("FirmaKeyR2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Firma_KeyR2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    b.Property<string>("NombresOdontologo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NombresOdontologo");

                    b.Property<string>("TelefonoOdontologo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TelefonoOdontologo");

                    b.HasKey("IdDatosRecetario");

                    b.ToTable("DatosRecetario", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.Endodoncia", b =>
                {
                    b.Property<int>("IdEndodoncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Endodoncia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEndodoncia"));

                    b.Property<string>("Cuspide")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Cuspide");

                    b.Property<int?>("Diametro")
                        .HasColumnType("int")
                        .HasColumnName("Diametro");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int")
                        .HasColumnName("ID_Paciente");

                    b.Property<int?>("Mm1")
                        .HasColumnType("int")
                        .HasColumnName("MM1");

                    b.Property<int?>("Mm2")
                        .HasColumnType("int")
                        .HasColumnName("MM2");

                    b.Property<int?>("Mm3")
                        .HasColumnType("int")
                        .HasColumnName("MM3");

                    b.Property<int?>("Mm4")
                        .HasColumnType("int")
                        .HasColumnName("MM4");

                    b.Property<string>("ObservacionesEndodoncia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ObservacionesEndodoncia");

                    b.Property<string>("ObservacionesTxPeriodontal")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ObservacionesTxPeriodontal");

                    b.Property<bool>("Obturacion")
                        .HasColumnType("bit")
                        .HasColumnName("Obturacion");

                    b.Property<string>("Pieza")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Pieza");

                    b.Property<bool>("TxPeriodontal")
                        .HasColumnType("bit")
                        .HasColumnName("TxPeriodontal");

                    b.HasKey("IdEndodoncia");

                    b.ToTable("Endodoncia", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.EstadoCita", b =>
                {
                    b.Property<int>("IdEstadoCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_EstadoCita");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoCita"));

                    b.Property<string>("TipoEstadoCita")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TipoEstadoCita");

                    b.HasKey("IdEstadoCita");

                    b.ToTable("EstadoCita", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.EstadoTratamiento", b =>
                {
                    b.Property<int>("IdEstadoTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_EstadoTratamiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoTratamiento"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EstadoTratamiento");

                    b.HasKey("IdEstadoTratamiento");

                    b.ToTable("EstadoTratamiento", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.HistoriaCondicion", b =>
                {
                    b.Property<int>("IdHistoriaCondicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_HistoriaCondicion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistoriaCondicion"));

                    b.Property<int>("IdCondicion")
                        .HasColumnType("int")
                        .HasColumnName("ID_Condicion");

                    b.Property<int>("IdHistoriaMedica")
                        .HasColumnType("int")
                        .HasColumnName("ID_HistoriaMedica");

                    b.Property<string>("ObservacionCondicion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("ObservacionCondicion");

                    b.HasKey("IdHistoriaCondicion");

                    b.HasIndex("IdCondicion");

                    b.HasIndex("IdHistoriaMedica", "IdCondicion")
                        .IsUnique();

                    b.ToTable("Historia_Condicion", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.HistoriaMedica", b =>
                {
                    b.Property<int>("IdHistoriaMedica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_HistoriaMedica");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistoriaMedica"));

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int")
                        .HasColumnName("ID_Paciente");

                    b.Property<string>("ObservacionesGenerales")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Observaciones_Generales");

                    b.HasKey("IdHistoriaMedica");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("Historia_Medica", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.MedicamentoReceta", b =>
                {
                    b.Property<int>("IdMedicamentosReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_MedicamentosReceta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicamentosReceta"));

                    b.Property<int>("IdRecetario")
                        .HasColumnType("int")
                        .HasColumnName("ID_Recetario");

                    b.Property<string>("IndicacionesReceta")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("IndicacionesReceta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("MedicamentoReceta");

                    b.Property<string>("PresentacionReceta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PresentacionReceta");

                    b.HasKey("IdMedicamentosReceta");

                    b.HasIndex("IdRecetario");

                    b.ToTable("MedicamentosReceta", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Paciente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Apellidos");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Direccion");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Nacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Registro");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("NIT");

                    b.Property<string>("NombreEncargado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre_Encargado");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombres");

                    b.Property<string>("Sexo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Sexo");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono");

                    b.Property<string>("TelefonoEncargado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefono_Encargado");

                    b.HasKey("IdPaciente");

                    b.ToTable("Paciente", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.Panoramica", b =>
                {
                    b.Property<int>("IdPanoramica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Panoramica");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPanoramica"));

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Eliminacion");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Subida")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int")
                        .HasColumnName("ID_Paciente");

                    b.Property<string>("KeyPanoramicaR2")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Key_PanoramicaR2");

                    b.HasKey("IdPanoramica");

                    b.HasIndex("IdPaciente", "FechaEliminacion")
                        .HasDatabaseName("IX_Panoramicas_Paciente_Activas");

                    b.ToTable("Panoramicas", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.PlanTratamiento", b =>
                {
                    b.Property<int>("IdPlanTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PlanTratamiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanTratamiento"));

                    b.Property<DateTime?>("FechaFinTratamiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaFinTratamiento");

                    b.Property<DateTime>("FechaRegistroPlan")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaRegistroPlan");

                    b.Property<int>("IdEstadoTratamiento")
                        .HasColumnType("int")
                        .HasColumnName("ID_EstadoTratamiento");

                    b.Property<int>("IdPresupuestoPlan")
                        .HasColumnType("int")
                        .HasColumnName("ID_PresupuestoPlan");

                    b.Property<string>("Pieza")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Pieza");

                    b.Property<string>("Tratamiento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Tratamiento");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdPlanTratamiento");

                    b.HasIndex("IdEstadoTratamiento");

                    b.HasIndex("IdPresupuestoPlan", "Pieza")
                        .IsUnique();

                    b.ToTable("PlanTratamiento", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.PresupuestoPlan", b =>
                {
                    b.Property<int>("IdPresupuestoPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PresupuestoPlan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPresupuestoPlan"));

                    b.Property<decimal?>("CantidadDescuento")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CantidadDescuento");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCierre");

                    b.Property<DateTime>("FechaInicioPlan")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaInicioPlan");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int")
                        .HasColumnName("ID_Paciente");

                    b.Property<string>("ObservacionesGenerales")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("ObservacionesGenerales");

                    b.HasKey("IdPresupuestoPlan");

                    b.HasIndex("IdPaciente")
                        .IsUnique()
                        .HasFilter("[FechaCierre] IS NULL");

                    b.ToTable("PresupuestoPlan", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.Protesis", b =>
                {
                    b.Property<int>("IdProtesis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Protesis");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProtesis"));

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int")
                        .HasColumnName("ID_Paciente");

                    b.Property<string>("ObservacionesProtesis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ObservacionesProtesis");

                    b.Property<bool>("PPF")
                        .HasColumnType("bit")
                        .HasColumnName("PPF");

                    b.Property<bool>("PPRInf")
                        .HasColumnType("bit")
                        .HasColumnName("PPRInf");

                    b.Property<bool>("PPRSup")
                        .HasColumnType("bit")
                        .HasColumnName("PPRSup");

                    b.Property<bool>("PTInf")
                        .HasColumnType("bit")
                        .HasColumnName("PT_Inf");

                    b.Property<bool>("PTSup")
                        .HasColumnType("bit")
                        .HasColumnName("PT_Sup");

                    b.HasKey("IdProtesis");

                    b.ToTable("Protesis", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.Recetario", b =>
                {
                    b.Property<int>("IdRecetario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Recetario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecetario"));

                    b.Property<DateTime>("FechaEmisionRecetario")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEmisionRecetario");

                    b.Property<int>("IdDatosRecetario")
                        .HasColumnType("int")
                        .HasColumnName("ID_DatosRecetario");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int")
                        .HasColumnName("ID_Paciente");

                    b.Property<string>("NotasAdicionalesRecetario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NotasAdicionalesRecetario");

                    b.HasKey("IdRecetario");

                    b.HasIndex("IdDatosRecetario");

                    b.HasIndex("IdPaciente");

                    b.ToTable("Recetario", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreRol");

                    b.HasKey("IdRol");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Contrasena_Hash");

                    b.Property<string>("CorreoUsuario")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CorreoUsuario");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("EsAdmin");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("ID_Rol");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NombreUsuario");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("Salt");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("UltimoAcceso");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Peredent.Api.Models.BloqueoAgenda", b =>
                {
                    b.HasOne("Peredent.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Peredent.Api.Models.Cita", b =>
                {
                    b.HasOne("Peredent.Api.Models.EstadoCita", "EstadoCita")
                        .WithMany()
                        .HasForeignKey("IdEstadoCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peredent.Api.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peredent.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoCita");

                    b.Navigation("Paciente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Peredent.Api.Models.HistoriaCondicion", b =>
                {
                    b.HasOne("Peredent.Api.Models.Condicion", "Condicion")
                        .WithMany()
                        .HasForeignKey("IdCondicion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peredent.Api.Models.HistoriaMedica", null)
                        .WithMany("Condiciones")
                        .HasForeignKey("IdHistoriaMedica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condicion");
                });

            modelBuilder.Entity("Peredent.Api.Models.MedicamentoReceta", b =>
                {
                    b.HasOne("Peredent.Api.Models.Recetario", null)
                        .WithMany("Medicamentos")
                        .HasForeignKey("IdRecetario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peredent.Api.Models.Panoramica", b =>
                {
                    b.HasOne("Peredent.Api.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Panoramicas_Paciente");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Peredent.Api.Models.PlanTratamiento", b =>
                {
                    b.HasOne("Peredent.Api.Models.EstadoTratamiento", "EstadoTratamiento")
                        .WithMany()
                        .HasForeignKey("IdEstadoTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peredent.Api.Models.PresupuestoPlan", null)
                        .WithMany("Piezas")
                        .HasForeignKey("IdPresupuestoPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoTratamiento");
                });

            modelBuilder.Entity("Peredent.Api.Models.Recetario", b =>
                {
                    b.HasOne("Peredent.Api.Models.DatosRecetario", "DatosRecetario")
                        .WithMany()
                        .HasForeignKey("IdDatosRecetario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peredent.Api.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatosRecetario");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Peredent.Api.Models.Usuario", b =>
                {
                    b.HasOne("Peredent.Api.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Peredent.Api.Models.HistoriaMedica", b =>
                {
                    b.Navigation("Condiciones");
                });

            modelBuilder.Entity("Peredent.Api.Models.PresupuestoPlan", b =>
                {
                    b.Navigation("Piezas");
                });

            modelBuilder.Entity("Peredent.Api.Models.Recetario", b =>
                {
                    b.Navigation("Medicamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
