// Numeración de piezas dentales usada por la clínica: piezas permanentes 1-32
// y, cuando corresponde a la posición de una pieza primaria, su letra A-T.
export const PIEZAS_DENTALES = [
  { numero: 1, etiqueta: '1' },
  { numero: 2, etiqueta: '2' },
  { numero: 3, etiqueta: '3' },
  { numero: 4, etiqueta: '4a' },
  { numero: 5, etiqueta: '5b' },
  { numero: 6, etiqueta: '6c' },
  { numero: 7, etiqueta: '7d' },
  { numero: 8, etiqueta: '8e' },
  { numero: 9, etiqueta: '9f' },
  { numero: 10, etiqueta: '10g' },
  { numero: 11, etiqueta: '11h' },
  { numero: 12, etiqueta: '12i' },
  { numero: 13, etiqueta: '13j' },
  { numero: 14, etiqueta: '14' },
  { numero: 15, etiqueta: '15' },
  { numero: 16, etiqueta: '16' },
  { numero: 17, etiqueta: '17' },
  { numero: 18, etiqueta: '18' },
  { numero: 19, etiqueta: '19' },
  { numero: 20, etiqueta: '20' },
  { numero: 21, etiqueta: '21l' },
  { numero: 22, etiqueta: '22m' },
  { numero: 23, etiqueta: '23n' },
  { numero: 24, etiqueta: '24o' },
  { numero: 25, etiqueta: '25p' },
  { numero: 26, etiqueta: '26q' },
  { numero: 27, etiqueta: '27r' },
  { numero: 28, etiqueta: '28s' },
  { numero: 29, etiqueta: '29t' },
  { numero: 30, etiqueta: '30' },
  { numero: 31, etiqueta: '31' },
  { numero: 32, etiqueta: '32' },
];
